### ISSUE TITLE
Inconsistent Dataset Path structure

### ISSUE THREAD

**Issue by arpita8** [AIVIETNAMResearch/AI-City-2024-Track2#1]
The path you have provided in the readme is not consistent with the path you have used in the code, So if you can please correct it.

**Comment by trinhxuankhai** [comment]
Thank you for pointing this out. Could you please specify which path in the readme doesn't match the one used in the code? This will help me ensure that I correct the right information.

**Comment by arpita8** [comment]
In the readme the structure are not correct compared to the structure used in extract_frames_external.py

**Comment by trinhxuankhai** [comment]
The dataset structure in the readme has been corrected. If you have any further inquiries or requirements, please let me know.
