### ISSUE TITLE
Specify the version of the module in requirement.txt

### ISSUE THREAD

**Issue by arpita8** [AIVIETNAMResearch/AI-City-2024-Track2#2]
Can you please provide the version on the module in your ```requirement.txt ```inside ```src/preprocess/segment_extraction/requirement.txt``` 
These are the module , which I want to know what version you have used.
```
transformers
numpy
torcheval
sentence_transformers
accelerate
vllm
setuptools 
wheel
spacy
```
Can you please also let me know what  ```CUDA``` and ```Python``` version you are using for executing your code as well.

**Comment by trinhxuankhai** [comment]
I have updated the requirements.txt and readme file within src/preprocess/segment_extraction to specify the versions of the modules utilized. If you require further clarification or assistance, please let me know.

**Comment by trinhxuankhai** [comment]
I additionally include a Dockerfile to simplify the environment setup.
